{{- if and .Values.ssl.enabled .Values.ssl.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ssl.secretName | default (printf "%s-ssl" (include "vscode-offline.fullname" .)) }}
  labels:
    {{- include "vscode-offline.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.ssl.certificate }}
  vscoffline.crt: {{ .Values.ssl.certificate | b64enc | quote }}
  {{- else }}
  # Default self-signed certificate (generated in chart)
  vscoffline.crt: |
    {{- (.Files.Get "files/vscoffline.crt") | b64enc | nindent 4 }}
  {{- end }}
  {{- if .Values.ssl.privateKey }}
  vscoffline.key: {{ .Values.ssl.privateKey | b64enc | quote }}
  {{- else }}
  # Default private key (generated in chart)
  vscoffline.key: |
    {{- (.Files.Get "files/vscoffline.key") | b64enc | nindent 4 }}
  {{- end }}
{{- end }}